#!/bin/bash

echo "Enter the file name :"
read file_name


touch $file_name

echo "#!/bin/bash" > $file_name

echo "Enter the desired command :"
read desired_command

echo $desired_command >> $file_name

chmod u+x $file_name
